mainsetup finished
cristianoprogramador/BE_SF pull request #2
Opened 2023-07-11 12:01 UTC by cristianoprogramador

finished all the type problems and did a new test without changing the backend server

2023-07-11 19:47 UTC, RenatoTMLima requested changes

2023-07-11 19:47 UTC, RenatoTMLima commented on prisma/schema.prisma
>    userProjects UserProjectRelation[]
Are all of these columns required, or we should have some optional ones? If we do, please append a ? question mark to those that are optional. The same goes for the rest of the file, like the Project table

2023-07-11 19:47 UTC, RenatoTMLima commented on src/domain/Projects/repositories/projectRepository.ts
>  export const projectRepository = {
Could you refactor it to be a Class? Since we are going to use dependency injection and here you're kinda creating an object of functions, it would be more concise to use OOP, having the class ProjectRepository and its constructor, and methods.

2023-07-11 19:47 UTC, RenatoTMLima commented on src/index.ts
> +import { ApolloServer } from "apollo-server";
Suggestion: remove imports from apollo-server to start using @apollo/server

2023-07-11 19:47 UTC, RenatoTMLima commented on src/domain/Projects/resolvers/projectResolvers.ts
>      },
Each resolver is using different approaches to resolve the query/mutation. Some is using prisma directly, other are using services. Keep consistency. I suggest creating a controller class, where you have all the resolvers methods, and each one will use services, and each service will use the corresponding repository method.

2023-07-11 19:47 UTC, RenatoTMLima commented on src/domain/Projects/services/projectService.ts
>  export const projectService = {
Refactor it to be a class with single responsibility. It could be class CreateProjectService and have a method execute, where the logic would handle the creation of a project, using the ProjectsRepository.

2023-07-11 19:47 UTC, RenatoTMLima commented on src/domain/Users/repositories/userRepository.ts
>  export const userRepository = {
Same comment as the other repository, make it a class.

2023-07-11 19:47 UTC, RenatoTMLima commented on src/domain/Users/resolvers/userResolvers.ts
>  export const userResolvers = {
Same comment from the project resolver, create a controller to be used here

2023-07-11 19:47 UTC, RenatoTMLima commented on src/domain/Users/services/userService.ts
>  export const userService = {
Same comment as the project service, create a class with a single method

2023-07-11 21:06 UTC, RenatoTMLima commented
We need to remove package apollo-server to use @apollo/server in its place. For graphql types that are using the gql function, since @apollo/server doesn't exports it, we will need to add the following dependency, as per Apollo Server documentation: graphql-tag.

Here's the reference: https://www.apollographql.com/docs/apollo-server/migration#gql-graphql-tag
![image](https://github.com/cristianoprogramador/BE_SH/assets/49873623/eca9c0cb-6f7d-4741-8aec-2dfe56a11963)

2023-07-18 14:09 UTC, cristianoprogramador commented on prisma/schema.prisma
>    userProjects UserProjectRelation[]
I changed that

2023-07-18 14:10 UTC, cristianoprogramador commented on src/domain/Projects/repositories/projectRepository.ts
>  export const projectRepository = {
We did that together, thanks for that

2023-07-18 14:10 UTC, cristianoprogramador commented on src/index.ts
> +import { ApolloServer } from "apollo-server";
i started using @apollo/server

2023-07-18 14:10 UTC, cristianoprogramador commented on src/domain/Projects/resolvers/projectResolvers.ts
>      },
We that together also

2023-07-20 01:10 UTC, RenatoTMLima approved these changes

2023-07-20 01:10 UTC, merged